version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 0.14.9
    commands:
      - echo "Installing Terraform..."
      - curl -O https://releases.hashicorp.com/terraform/0.14.9/terraform_0.14.9_linux_amd64.zip
      - unzip terraform_0.14.9_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Applying Terraform..."
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform apply complete."
artifacts:
  files:
    - '**/*'
